{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "paas-java-demo.serviceAccountName" . }}
  labels:
    {{- include "paas-java-demo.labels" . | nindent 4 }}
{{- end -}}
