apiVersion: v1
appVersion: 5.2.0
description: paas-java-demo Helm chart for Kubernetes
home: https://leoxhj.github.io/paas-java-demo
maintainers:
- email: leoxhj@users.noreply.github.com
  name: leoxhj
name: paas-java-demo
sources:
- https://github.com/leoxhj/paas-java-demo
version: 5.2.0
